--------------------------------------------------------
--  Arquivo criado - quarta-feira-junho-27-2018   
--------------------------------------------------------
@/Users/joseluis/SEQUENCES/APEX__WS_SEQ.sql
@/Users/joseluis/SEQUENCES/DEMO_CUST_SEQ.sql
@/Users/joseluis/SEQUENCES/DEMO_ORDER_ITEMS_SEQ.sql
@/Users/joseluis/SEQUENCES/DEMO_ORD_SEQ.sql
@/Users/joseluis/SEQUENCES/DEMO_PROD_SEQ.sql
@/Users/joseluis/SEQUENCES/DEPT_SEQ.sql
@/Users/joseluis/SEQUENCES/EMP_SEQ.sql
@/Users/joseluis/SEQUENCES/SEQ_CLIENTE.sql
@/Users/joseluis/SEQUENCES/SEQ_TURNO.sql
@/Users/joseluis/TABLES/ALL_CIDADE.sql
@/Users/joseluis/TABLES/ALL_ESTADOS.sql
@/Users/joseluis/TABLES/ALL_PAIS.sql
@/Users/joseluis/TABLES/APEX__ACL.sql
@/Users/joseluis/TABLES/APEX_TEAM_DEV_FILES.sql
@/Users/joseluis/TABLES/APEX__WS_FILES.sql
@/Users/joseluis/TABLES/APEX__WS_HISTORY.sql
@/Users/joseluis/TABLES/APEX__WS_LINKS.sql
@/Users/joseluis/TABLES/APEX__WS_NOTES.sql
@/Users/joseluis/TABLES/APEX__WS_ROWS.sql
@/Users/joseluis/TABLES/APEX__WS_TAGS.sql
@/Users/joseluis/TABLES/APEX__WS_WEBPG_SECTION_HISTORY.sql
@/Users/joseluis/TABLES/APEX__WS_WEBPG_SECTIONS.sql
@/Users/joseluis/TABLES/CLIENTE.sql
@/Users/joseluis/TABLES/CLIENTE_AGENDA.sql
@/Users/joseluis/TABLES/CLIENTE_CALENDARIO.sql
@/Users/joseluis/TABLES/CLIENTE_CONTRATO.sql
@/Users/joseluis/TABLES/CLIENTE_FABRICANTE.sql
@/Users/joseluis/TABLES/CLIENTE_GRUPO.sql
@/Users/joseluis/TABLES/CLIENTE_MAQUINA.sql
@/Users/joseluis/TABLES/CLIENTE_MAQUINA_ARQUIVO.sql
@/Users/joseluis/TABLES/CLIENTE_MAQUINA_CKLIST.sql
@/Users/joseluis/TABLES/CLIENTE_MAQUINA_CKLIST_ITEM.sql
@/Users/joseluis/TABLES/CLIENTE_MAQUINA_CKLIST_ITEM_OS.sql
@/Users/joseluis/TABLES/CLIENTE_MAQUINA_GRUPO.sql
@/Users/joseluis/TABLES/CLIENTE_MAQUINA_TRO.sql
@/Users/joseluis/TABLES/CLIENTE_NOTIFICA.sql
@/Users/joseluis/TABLES/CLIENTE_OS.sql
@/Users/joseluis/TABLES/CLIENTE_OS_ARQUIVO.sql
@/Users/joseluis/TABLES/CLIENTE_OS_CLASS.sql
@/Users/joseluis/TABLES/CLIENTE_OS_DATE_TMP.sql
@/Users/joseluis/TABLES/CLIENTE_OS_EVENTO.sql
@/Users/joseluis/TABLES/CLIENTE_OS_MATERIAL.sql
@/Users/joseluis/TABLES/CLIENTE_OS_POSM.sql
@/Users/joseluis/TABLES/CLIENTE_TIPO_MANUTENCAO.sql
@/Users/joseluis/TABLES/CLIENTE_TURNO.sql
@/Users/joseluis/TABLES/CLIENTE_USUARIO.sql
@/Users/joseluis/TABLES/DEMO_CONSTRAINT_LOOKUP.sql
@/Users/joseluis/TABLES/DEMO_CUSTOMERS.sql
@/Users/joseluis/TABLES/DEMO_ORDER_ITEMS.sql
@/Users/joseluis/TABLES/DEMO_ORDERS.sql
@/Users/joseluis/TABLES/DEMO_PRODUCT_INFO.sql
@/Users/joseluis/TABLES/DEMO_STATES.sql
@/Users/joseluis/TABLES/DEMO_TAGS.sql
@/Users/joseluis/TABLES/DEMO_TAGS_SUM.sql
@/Users/joseluis/TABLES/DEMO_TAGS_TYPE_SUM.sql
@/Users/joseluis/TABLES/DEPT.sql
@/Users/joseluis/TABLES/EMP.sql
@/Users/joseluis/TABLES/HTMLDB_PLAN_TABLE.sql
@/Users/joseluis/TABLES/MENU_ADM.sql
@/Users/joseluis/TABLES/PARAM_OS_EVENTO_TIPO.sql
@/Users/joseluis/TABLES/PARAM_OS_STATUS.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_MAQUINA_CHECKLIST.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_OS.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_OS_INDICADORES.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_OS_INDICES.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_OS_NOC.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_OS_NOP.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_OS_OPP.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_OS_QOS.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_PROGRAMACAO_DIA.sql
@/Users/joseluis/VIEWS/VW_CLIENTE_TRO.sql
@/Users/joseluis/INDEXES/DEMO_PRODUCT_INFO_PK.sql
@/Users/joseluis/INDEXES/DEMO_PRODUCT_INFO_UK.sql
@/Users/joseluis/INDEXES/DEMO_TAGS_SUM_PK.sql
@/Users/joseluis/INDEXES/DEMO_TAGS_TYPE_SUM_PK.sql
@/Users/joseluis/INDEXES/IX_CLIENTE_CNPJ.sql
@/Users/joseluis/INDEXES/PK_ALL_CIDADE.sql
@/Users/joseluis/INDEXES/PK_ALL_ESTADO.sql
@/Users/joseluis/INDEXES/PK_ALL_PAIS.sql
@/Users/joseluis/INDEXES/PK_CLIENTE.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_AGENDA.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_CALENDARIO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_FABRICANTE.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_GRUPO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_MAQUINA.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_MAQUINA_ARQUIVO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_MAQUINA_CKLIST.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_MAQ_CKLIST_ITEM.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_MAQ_GRUPO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_MAQ_TRO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_NOTIFICA.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_OS_ARQUIVO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_OS_CLASS.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_OS_EVENTO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_OS_MATERIAL.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_OS_POSM.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_TIPO_MANUT.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_TURNO.sql
@/Users/joseluis/INDEXES/PK_CLIENTE_USUARIO.sql
@/Users/joseluis/INDEXES/PK_GOS_ORDEM_SERVICO.sql
@/Users/joseluis/INDEXES/PK_MENU_ADM.sql
@/Users/joseluis/INDEXES/PK_PARAM_OS_EVENTO_TIPO.sql
@/Users/joseluis/INDEXES/PK_PARAM_OS_STATUS.sql
@/Users/joseluis/INDEXES/APEX__ACL_PK.sql
@/Users/joseluis/INDEXES/APEX__WS_FILES_PK.sql
@/Users/joseluis/INDEXES/APEX__WS_LINKS_PK.sql
@/Users/joseluis/INDEXES/APEX__WS_NOTES_PK.sql
@/Users/joseluis/INDEXES/APEX__WS_ROWS_PK.sql
@/Users/joseluis/INDEXES/APEX__WS_ROWS_UK1.sql
@/Users/joseluis/INDEXES/APEX__WS_TAGS_PK.sql
@/Users/joseluis/INDEXES/APEX__WS_WEBPG_SECTIONS_PK.sql
@/Users/joseluis/INDEXES/CLIENTE_CONTRATO_PK.sql
@/Users/joseluis/INDEXES/DEMO_CUSTOMERS_PK.sql
@/Users/joseluis/INDEXES/DEMO_CUSTOMERS_UK.sql
@/Users/joseluis/INDEXES/DEMO_ORDER_ITEMS_PK.sql
@/Users/joseluis/INDEXES/DEMO_ORDER_ITEMS_UK.sql
@/Users/joseluis/INDEXES/DEMO_ORDER_PK.sql
@/Users/joseluis/INDEXES/UN_CLIENTE_EMAIL.sql
@/Users/joseluis/INDEXES/APEX__WS_ROWS_IDX.sql
@/Users/joseluis/INDEXES/DEMO_CUST_NAME_IX.sql
@/Users/joseluis/INDEXES/APEX__WS_LINKS_IDX1.sql
@/Users/joseluis/INDEXES/APEX__WS_TAGS_IDX1.sql
@/Users/joseluis/INDEXES/APEX__WS_WEBPG_SECHIST_IDX1.sql
@/Users/joseluis/INDEXES/DEMO_ORD_CUSTOMER_IX.sql
@/Users/joseluis/INDEXES/APEX__WS_LINKS_IDX2.sql
@/Users/joseluis/INDEXES/IX_CLIENTE_OS_EVENTO.sql
@/Users/joseluis/INDEXES/IX_ALL_CIDADE_UF.sql
@/Users/joseluis/INDEXES/APEX__WS_TAGS_IDX2.sql
@/Users/joseluis/INDEXES/APEX__ACL_IDX1.sql
@/Users/joseluis/INDEXES/APEX__WS_NOTES_IDX2.sql
@/Users/joseluis/INDEXES/APEX__WS_FILES_IDX2.sql
@/Users/joseluis/INDEXES/APEX__WS_NOTES_IDX1.sql
@/Users/joseluis/INDEXES/APEX__WS_HISTORY_IDX.sql
@/Users/joseluis/INDEXES/APEX__WS_FILES_IDX1.sql
@/Users/joseluis/TRIGGERS/APEX__ACL_T1.sql
@/Users/joseluis/TRIGGERS/APEX_TEAM_DEV_FILES_BIU.sql
@/Users/joseluis/TRIGGERS/APEX__WS_FILES_T1.sql
@/Users/joseluis/TRIGGERS/APEX__WS_LINKS_T1.sql
@/Users/joseluis/TRIGGERS/APEX__WS_NOTES_T1.sql
@/Users/joseluis/TRIGGERS/APEX__WS_ROWS_T1.sql
@/Users/joseluis/TRIGGERS/APEX__WS_TAGS_T1.sql
@/Users/joseluis/TRIGGERS/APEX__WS_WEBPG_SECTIONS_T1.sql
@/Users/joseluis/TRIGGERS/DEMO_CUSTOMERS_BD.sql
@/Users/joseluis/TRIGGERS/DEMO_CUSTOMERS_BIU.sql
@/Users/joseluis/TRIGGERS/DEMO_ORDER_ITEMS_AIUD_TOTAL.sql
@/Users/joseluis/TRIGGERS/DEMO_ORDER_ITEMS_BI.sql
@/Users/joseluis/TRIGGERS/DEMO_ORDER_ITEMS_BIU_GET_PRICE.sql
@/Users/joseluis/TRIGGERS/DEMO_ORDERS_BD.sql
@/Users/joseluis/TRIGGERS/DEMO_ORDERS_BIU.sql
@/Users/joseluis/TRIGGERS/DEMO_PRODUCT_INFO_BD.sql
@/Users/joseluis/TRIGGERS/DEMO_PRODUCT_INFO_BIU.sql
@/Users/joseluis/TRIGGERS/DEMO_TAGS_BIU.sql
@/Users/joseluis/TRIGGERS/DEPT_TRG1.sql
@/Users/joseluis/TRIGGERS/EMP_TRG1.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_MAQ_CKLIST_ITEM_ID.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_NOTIFICA_ID.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_OS_ARQUIVO_ID.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_OS_CLASS_ID.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_OS_EVENTO.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_OS_EVENTO_ID.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_OS_MATERIAL_ID.sql
@/Users/joseluis/TRIGGERS/TR_CLIENTE_OS_POSM_ID.sql
@/Users/joseluis/TRIGGERS/TR_MENU_ADM_ID.sql
@/Users/joseluis/PROCEDURES/PR_SEND_MAIL.sql
@/Users/joseluis/PROCEDURES/PR_SEND_NOTIFICACAO.sql
@/Users/joseluis/PACKAGES/PCK_ORDEM_SERVICO.sql
@/Users/joseluis/PACKAGES/PKG_SECURITY.sql
@/Users/joseluis/PACKAGES/SAMPLE_DATA_PKG.sql
@/Users/joseluis/PACKAGES/SAMPLE_PKG.sql
@/Users/joseluis/PACKAGE_BODIES/PCK_ORDEM_SERVICO.sql
@/Users/joseluis/PACKAGE_BODIES/PKG_SECURITY.sql
@/Users/joseluis/PACKAGE_BODIES/SAMPLE_DATA_PKG.sql
@/Users/joseluis/PACKAGE_BODIES/SAMPLE_PKG.sql
@/Users/joseluis/FUNCTIONS/FU_DATEDIFF.sql
@/Users/joseluis/FUNCTIONS/FU_SHOWDATE.sql
@/Users/joseluis/FUNCTIONS/LDAP_SECURITY_APEX_SPO.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_HISTORY.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_MAQUINA_GRUPO.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_OS_CLASS.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_TIPO_MANUTENCAO.sql
@/Users/joseluis/CONSTRAINTS/DEMO_CONSTRAINT_LOOKUP.sql
@/Users/joseluis/CONSTRAINTS/ALL_CIDADE.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_TAGS.sql
@/Users/joseluis/CONSTRAINTS/DEMO_PRODUCT_INFO.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_CALENDARIO.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_CONTRATO.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_OS_EVENTO.sql
@/Users/joseluis/CONSTRAINTS/EMP.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_MAQUINA_ARQUIVO.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_MAQUINA_TRO.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_OS.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_OS_MATERIAL.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_USUARIO.sql
@/Users/joseluis/CONSTRAINTS/DEMO_ORDERS.sql
@/Users/joseluis/CONSTRAINTS/DEPT.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_LINKS.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_FABRICANTE.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_MAQUINA_CKLIST.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_TURNO.sql
@/Users/joseluis/CONSTRAINTS/DEMO_TAGS.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_FILES.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_WEBPG_SECTIONS.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_MAQUINA_CKLIST_ITEM_OS.sql
@/Users/joseluis/CONSTRAINTS/PARAM_OS_EVENTO_TIPO.sql
@/Users/joseluis/CONSTRAINTS/ALL_ESTADOS.sql
@/Users/joseluis/CONSTRAINTS/DEMO_ORDER_ITEMS.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_WEBPG_SECTION_HISTORY.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_GRUPO.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_NOTIFICA.sql
@/Users/joseluis/CONSTRAINTS/DEMO_TAGS_TYPE_SUM.sql
@/Users/joseluis/CONSTRAINTS/ALL_PAIS.sql
@/Users/joseluis/CONSTRAINTS/APEX__ACL.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_MAQUINA.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_OS_ARQUIVO.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_ROWS.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_AGENDA.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_OS_POSM.sql
@/Users/joseluis/CONSTRAINTS/DEMO_TAGS_SUM.sql
@/Users/joseluis/CONSTRAINTS/MENU_ADM.sql
@/Users/joseluis/CONSTRAINTS/DEMO_CUSTOMERS.sql
@/Users/joseluis/CONSTRAINTS/APEX_TEAM_DEV_FILES.sql
@/Users/joseluis/CONSTRAINTS/APEX__WS_NOTES.sql
@/Users/joseluis/CONSTRAINTS/CLIENTE_MAQUINA_CKLIST_ITEM.sql
@/Users/joseluis/CONSTRAINTS/PARAM_OS_STATUS.sql
@/Users/joseluis/REF_CONSTRAINTS/ALL_CIDADE.sql
@/Users/joseluis/REF_CONSTRAINTS/APEX__WS_FILES.sql
@/Users/joseluis/REF_CONSTRAINTS/APEX__WS_LINKS.sql
@/Users/joseluis/REF_CONSTRAINTS/APEX__WS_NOTES.sql
@/Users/joseluis/REF_CONSTRAINTS/APEX__WS_TAGS.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_CALENDARIO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_CONTRATO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_FABRICANTE.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_GRUPO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_MAQUINA.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_MAQUINA_CKLIST.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_MAQUINA_CKLIST_ITEM.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_MAQUINA_CKLIST_ITEM_OS.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_MAQUINA_TRO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_NOTIFICA.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_OS.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_OS_ARQUIVO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_OS_CLASS.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_OS_EVENTO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_OS_MATERIAL.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_OS_POSM.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_TIPO_MANUTENCAO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_TURNO.sql
@/Users/joseluis/REF_CONSTRAINTS/CLIENTE_USUARIO.sql
@/Users/joseluis/REF_CONSTRAINTS/DEMO_ORDER_ITEMS.sql
@/Users/joseluis/REF_CONSTRAINTS/DEMO_ORDERS.sql
@/Users/joseluis/REF_CONSTRAINTS/EMP.sql
@/Users/joseluis/REF_CONSTRAINTS/MENU_ADM.sql
@/Users/joseluis/REF_CONSTRAINTS/PARAM_OS_EVENTO_TIPO.sql
