--------------------------------------------------------
--  Ref Constraints for Table CLIENTE_OS
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_OS" ADD CONSTRAINT "FK_CLIENTE_OS_CLASS" FOREIGN KEY ("ID_CLIENTE", "ID_CLASS")
	  REFERENCES "WS4TI"."CLIENTE_OS_CLASS" ("ID_CLIENTE", "ID_CLASS") ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_OS" ADD CONSTRAINT "FK_CLIENTE_OS_GRUPO" FOREIGN KEY ("ID_CLIENTE", "ID_GRUPO")
	  REFERENCES "WS4TI"."CLIENTE_GRUPO" ("ID_CLIENTE", "ID_GRUPO") ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_OS" ADD CONSTRAINT "FK_CLIENTE_OS_MAQUINA" FOREIGN KEY ("ID_CLIENTE", "CD_MAQUINA")
	  REFERENCES "WS4TI"."CLIENTE_MAQUINA" ("ID_CLIENTE", "CD_MAQUINA") ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_OS" ADD CONSTRAINT "FK_CLIENTE_OS_STATUS" FOREIGN KEY ("ST_OS")
	  REFERENCES "WS4TI"."PARAM_OS_STATUS" ("ST_OS") ENABLE;
