--------------------------------------------------------
--  Constraints for Table CLIENTE_TURNO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_TURNO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_TURNO" MODIFY ("ID_TURNO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_TURNO" MODIFY ("NM_TURNO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_TURNO" ADD CONSTRAINT "PK_CLIENTE_TURNO" PRIMARY KEY ("ID_CLIENTE", "ID_TURNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
