--------------------------------------------------------
--  Constraints for Table CLIENTE_OS_POSM
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_OS_POSM" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_POSM" MODIFY ("ID_OS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_POSM" MODIFY ("ID_POSM" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_POSM" MODIFY ("FL_VALIDA_ENT" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_POSM" MODIFY ("FL_VALIDA_REC" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_POSM" ADD CONSTRAINT "PK_CLIENTE_OS_POSM" PRIMARY KEY ("ID_CLIENTE", "ID_OS", "ID_POSM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
