--------------------------------------------------------
--  Constraints for Table CLIENTE_MAQUINA_GRUPO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" MODIFY ("ID_MAQUINA_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" MODIFY ("DS_MAQUINA_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" MODIFY ("FL_HORIMETRO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" MODIFY ("FL_HORAS_CAL" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" MODIFY ("FL_MAQ_PARADAS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" MODIFY ("ST_MAQUINA_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" ADD CONSTRAINT "PK_CLIENTE_MAQ_GRUPO" PRIMARY KEY ("ID_CLIENTE", "ID_MAQUINA_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
