--------------------------------------------------------
--  Constraints for Table CLIENTE_USUARIO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" MODIFY ("NM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" MODIFY ("TP_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" MODIFY ("ST_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" ADD CONSTRAINT "PK_CLIENTE_USUARIO" PRIMARY KEY ("ID_CLIENTE", "CD_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" ADD CONSTRAINT "UN_CLIENTE_EMAIL" UNIQUE ("DS_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" ADD CONSTRAINT "CK_CLIENTE_USUARIO_STATUS" CHECK (st_usuario in('A','I')) ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_USUARIO" ADD CONSTRAINT "CK_CLIENTE_USUARIO_TIPO" CHECK (tp_usuario in('A','T','U')) ENABLE;
