--------------------------------------------------------
--  Constraints for Table CLIENTE_CONTRATO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" MODIFY ("QT_USUARIOS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" MODIFY ("DT_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" MODIFY ("DT_VENCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" ADD CONSTRAINT "CLIENTE_CONTRATO_PK" PRIMARY KEY ("ID_CONTRATO", "ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" ADD CONSTRAINT "CLIENTE_CONTRATO_CHK1" CHECK (ST_CONTRATO IN('A','I')) ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_CONTRATO" MODIFY ("ST_CONTRATO" NOT NULL ENABLE);
