--------------------------------------------------------
--  Constraints for Table CLIENTE_OS_CLASS
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_OS_CLASS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_CLASS" MODIFY ("ID_CLASS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_CLASS" MODIFY ("DS_CLASS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_CLASS" MODIFY ("ST_CLASS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_CLASS" ADD CONSTRAINT "PK_CLIENTE_OS_CLASS" PRIMARY KEY ("ID_CLIENTE", "ID_CLASS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
