--------------------------------------------------------
--  Constraints for Table CLIENTE_NOTIFICA
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_NOTIFICA" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_NOTIFICA" MODIFY ("ID_NOTIFICA" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_NOTIFICA" MODIFY ("DS_TITULO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_NOTIFICA" MODIFY ("DS_NOTIFICACAO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_NOTIFICA" MODIFY ("DT_ENVIO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_NOTIFICA" MODIFY ("FL_LIDO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_NOTIFICA" ADD CONSTRAINT "PK_CLIENTE_NOTIFICA" PRIMARY KEY ("ID_CLIENTE", "ID_NOTIFICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
