--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE" MODIFY ("DS_RAZAO_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE" MODIFY ("DT_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE" MODIFY ("ST_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE" ADD CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE" ADD CONSTRAINT "IX_CLIENTE_CNPJ" UNIQUE ("NR_CNPJ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE" ADD CONSTRAINT "CK_CLIENTE_STATUS" CHECK (st_cliente in('A','I')) ENABLE;
