--------------------------------------------------------
--  Constraints for Table CLIENTE_TIPO_MANUTENCAO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_TIPO_MANUTENCAO" ADD CONSTRAINT "PK_CLIENTE_TIPO_MANUT" PRIMARY KEY ("ID_CLIENTE", "CD_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_TIPO_MANUTENCAO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_TIPO_MANUTENCAO" MODIFY ("CD_TIPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_TIPO_MANUTENCAO" MODIFY ("DS_TIPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_TIPO_MANUTENCAO" MODIFY ("ST_TIPO" NOT NULL ENABLE);
