--------------------------------------------------------
--  Constraints for Table CLIENTE_OS_EVENTO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_OS_EVENTO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_EVENTO" MODIFY ("ID_OS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_EVENTO" MODIFY ("SQ_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_EVENTO" MODIFY ("DT_ABRE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_EVENTO" MODIFY ("LS_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS_EVENTO" ADD CONSTRAINT "PK_CLIENTE_OS_EVENTO" PRIMARY KEY ("ID_CLIENTE", "ID_OS", "SQ_EVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
