--------------------------------------------------------
--  Constraints for Table CLIENTE_OS
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("ID_OS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("DT_OS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("FL_PARADO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("CD_TIPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("ST_OS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("FL_PRIORIDADE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("FL_AVALIACAO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_OS" ADD CONSTRAINT "PK_GOS_ORDEM_SERVICO" PRIMARY KEY ("ID_CLIENTE", "ID_OS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_OS" ADD CONSTRAINT "CK_CLIENTE_OS_FL_PRIORIDADE" CHECK (fl_prioridade in('U','N')) ENABLE;
