--------------------------------------------------------
--  Constraints for Table CLIENTE_MAQUINA
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA" MODIFY ("CD_MAQUINA" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA" MODIFY ("DS_MAQUINA" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA" MODIFY ("ST_MAQUINA" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA" MODIFY ("FL_CKLIST_POSM" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA" ADD CONSTRAINT "PK_CLIENTE_MAQUINA" PRIMARY KEY ("ID_CLIENTE", "CD_MAQUINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
