--------------------------------------------------------
--  Constraints for Table CLIENTE_MAQUINA_ARQUIVO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_ARQUIVO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_ARQUIVO" MODIFY ("CD_MAQUINA" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_ARQUIVO" MODIFY ("ID_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_ARQUIVO" MODIFY ("DESCRICAO_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_ARQUIVO" MODIFY ("CONTEUDO_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_ARQUIVO" ADD CONSTRAINT "PK_CLIENTE_MAQUINA_ARQUIVO" PRIMARY KEY ("ID_CLIENTE", "CD_MAQUINA", "ID_ARQUIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
