--------------------------------------------------------
--  Constraints for Table CLIENTE_CALENDARIO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_CALENDARIO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_CALENDARIO" MODIFY ("DT_CALENDARIO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_CALENDARIO" ADD CONSTRAINT "PK_CLIENTE_CALENDARIO" PRIMARY KEY ("ID_CLIENTE", "DT_CALENDARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
