--------------------------------------------------------
--  Constraints for Table CLIENTE_GRUPO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" MODIFY ("NM_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" MODIFY ("FL_ENVIA_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" MODIFY ("ST_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" MODIFY ("FL_ATENDE_OS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" MODIFY ("FL_ATENDE_FSSC" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" ADD CONSTRAINT "PK_CLIENTE_GRUPO" PRIMARY KEY ("ID_CLIENTE", "ID_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
  ALTER TABLE "WS4TI"."CLIENTE_GRUPO" ADD CONSTRAINT "CK_CLIENTE_GRUPO_STATUS" CHECK (st_grupo in('A','I')) ENABLE;
