--------------------------------------------------------
--  Constraints for Table CLIENTE_MAQUINA_CKLIST_ITEM_OS
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" MODIFY ("QT_TEMPO_PREVISTO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" MODIFY ("CD_MAQUINA" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" MODIFY ("SQ_CHECKITEM" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" MODIFY ("ID_OS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" MODIFY ("DT_PROGRAMADA" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" MODIFY ("DT_LOG" NOT NULL ENABLE);
