--------------------------------------------------------
--  Constraints for Table CLIENTE_FABRICANTE
--------------------------------------------------------

  ALTER TABLE "WS4TI"."CLIENTE_FABRICANTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_FABRICANTE" MODIFY ("ID_FABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_FABRICANTE" MODIFY ("NM_FABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_FABRICANTE" MODIFY ("CD_PAIS" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."CLIENTE_FABRICANTE" ADD CONSTRAINT "PK_CLIENTE_FABRICANTE" PRIMARY KEY ("ID_CLIENTE", "ID_FABRICANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
