--------------------------------------------------------
--  Constraints for Table DEMO_TAGS
--------------------------------------------------------

  ALTER TABLE "WS4TI"."DEMO_TAGS" MODIFY ("TAG" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."DEMO_TAGS" ADD CONSTRAINT "DEMO_TAGS_CK" CHECK (content_type in ('CUSTOMER','ORDER','PRODUCT')) ENABLE;
  ALTER TABLE "WS4TI"."DEMO_TAGS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
