--------------------------------------------------------
--  Constraints for Table PARAM_OS_EVENTO_TIPO
--------------------------------------------------------

  ALTER TABLE "WS4TI"."PARAM_OS_EVENTO_TIPO" MODIFY ("TP_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."PARAM_OS_EVENTO_TIPO" MODIFY ("ST_TIPO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."PARAM_OS_EVENTO_TIPO" MODIFY ("FL_ATENDIMENTO" NOT NULL ENABLE);
  ALTER TABLE "WS4TI"."PARAM_OS_EVENTO_TIPO" ADD CONSTRAINT "PK_PARAM_OS_EVENTO_TIPO" PRIMARY KEY ("TP_EVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321"  ENABLE;
