--------------------------------------------------------
--  DDL for Table CLIENTE_MAQUINA_GRUPO
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_MAQUINA_GRUPO" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_MAQUINA_GRUPO" NUMBER, 
	"DS_MAQUINA_GRUPO" VARCHAR2(100 BYTE), 
	"FL_HORIMETRO" CHAR(1 BYTE) DEFAULT 'N', 
	"FL_HORAS_CAL" CHAR(1 BYTE) DEFAULT 'N', 
	"FL_MAQ_PARADAS" CHAR(1 BYTE) DEFAULT 'N', 
	"DS_EMAIL_RESP" VARCHAR2(350 BYTE), 
	"ST_MAQUINA_GRUPO" CHAR(1 BYTE) DEFAULT 'A', 
	"PK_ANTIGA_TABELA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_GRUPO"."FL_HORIMETRO" IS 'Máquina tem horímetro';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_GRUPO"."ST_MAQUINA_GRUPO" IS 'Ativo ou Inativo';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_GRUPO"."PK_ANTIGA_TABELA" IS 'Chave da antiga tabela';
