--------------------------------------------------------
--  DDL for Table CLIENTE_MAQUINA_CKLIST_ITEM
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM" 
   (	"ID_CLIENTE" NUMBER, 
	"CD_MAQUINA" VARCHAR2(15 BYTE), 
	"SQ_CHECKITEM" NUMBER, 
	"NR_ORDEM" NUMBER(4,0), 
	"DS_INSPECAO" VARCHAR2(400 BYTE), 
	"DS_OBS" VARCHAR2(200 BYTE), 
	"DT_CKECKITEM" DATE, 
	"DT_INICIO" DATE, 
	"DT_TERMINO" DATE, 
	"TP_RECORRENCIA" CHAR(3 BYTE), 
	"QT_RECORRENCIA" NUMBER, 
	"ST_CHECKITEM" CHAR(1 BYTE), 
	"ID_CKOS" NUMBER(2,0), 
	"CD_TIPO" VARCHAR2(3 BYTE) DEFAULT 'PRE', 
	"FL_PARADO" CHAR(1 BYTE) DEFAULT 'N', 
	"FL_PROGRAMAR" CHAR(1 BYTE) DEFAULT 'N', 
	"QT_TEMPO_PREVISTO" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM"."NR_ORDEM" IS 'Utilizado para Ordenar os ítens do checklist';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM"."TP_RECORRENCIA" IS '[NRE] NÃO RECORRENTE, [] , [RDI] DIARIO,  [RSE] SEMESTRAL, [RQZ] QUINZENAL, [RME] MENSAL, [RBM] BIMESTRAL, [RTM] TRIMESTRAL, [RSM] SEMESTRAL, [RAN] ANUAL, [RBE] BIENIO, [RTE] TRIENIO, [RQE] QUINQUENIO';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM"."QT_RECORRENCIA" IS 'Quantidade de tempo entre um evento e outro';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM"."CD_TIPO" IS 'Classificação do problema da OS';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM"."FL_PARADO" IS 'Máquina parada [S]IM ou [N]ÃO';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM"."FL_PROGRAMAR" IS 'Incluir na programação [N]ão / [S]im';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM"."QT_TEMPO_PREVISTO" IS 'Quantidade (Minutos) de tempo previsto de execução';
