--------------------------------------------------------
--  DDL for Table CLIENTE_OS_MATERIAL
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_OS_MATERIAL" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_OS" NUMBER, 
	"SQ_ITEM" NUMBER(8,0), 
	"DS_PRODUTO" VARCHAR2(400 BYTE), 
	"DS_FORNECEDOR" VARCHAR2(200 BYTE), 
	"VL_UNITARIO" NUMBER(12,2), 
	"QT_PRODUTO" NUMBER(16,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_MATERIAL"."ID_CLIENTE" IS 'PK OS';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_MATERIAL"."ID_OS" IS 'PK OS';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_MATERIAL"."SQ_ITEM" IS 'PK MATERIAL';
