--------------------------------------------------------
--  DDL for Table CLIENTE_MAQUINA
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_MAQUINA" 
   (	"ID_CLIENTE" NUMBER, 
	"CD_MAQUINA" VARCHAR2(15 BYTE), 
	"DS_MAQUINA" VARCHAR2(60 BYTE), 
	"ID_FABRICANTE" NUMBER, 
	"ID_MAQUINA_GRUPO" NUMBER, 
	"DS_DADOS_TECNICOS" VARCHAR2(1000 BYTE), 
	"DS_MODELO" VARCHAR2(50 BYTE), 
	"DS_SERIE" VARCHAR2(50 BYTE), 
	"NR_ANO_FABRICACAO" NUMBER(4,0), 
	"NR_POTENCIA" NUMBER(8,0), 
	"NR_TENSAO" NUMBER(8,0), 
	"DS_ATIVO_FISCAL" VARCHAR2(400 BYTE), 
	"ST_MAQUINA" CHAR(1 BYTE) DEFAULT 'A', 
	"FL_CKLIST_POSM" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA"."DS_ATIVO_FISCAL" IS 'Descrição do Ativo Fiscal';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA"."ST_MAQUINA" IS 'Ativo ou Inativo';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA"."FL_CKLIST_POSM" IS 'Check List Pós Manutenção';
