--------------------------------------------------------
--  DDL for Table CLIENTE_OS_POSM
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_OS_POSM" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_OS" NUMBER, 
	"ID_POSM" NUMBER, 
	"FL_APERTAR" CHAR(1 BYTE), 
	"FL_RECOLHER" CHAR(1 BYTE), 
	"FL_ORGANIZAR" CHAR(1 BYTE), 
	"DT_POSM" DATE, 
	"CD_USUARIO_ENT" VARCHAR2(50 BYTE), 
	"CD_USUARIO_REC" VARCHAR2(50 BYTE), 
	"DS_ENTREGA" VARCHAR2(200 BYTE), 
	"DS_RECEBE" VARCHAR2(200 BYTE), 
	"FL_VALIDA_ENT" CHAR(1 BYTE) DEFAULT 'N', 
	"FL_VALIDA_REC" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."FL_APERTAR" IS 'Validar apertos';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."FL_RECOLHER" IS 'Validar ferramentas recolhidas';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."FL_ORGANIZAR" IS 'Validar limpeza e organização';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."DT_POSM" IS 'Data entrega e recebimento';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."DS_ENTREGA" IS 'Detalhes entrega';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."DS_RECEBE" IS 'Detalhes recebto';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."FL_VALIDA_ENT" IS 'Validação senha usuario entrega';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_OS_POSM"."FL_VALIDA_REC" IS 'Validação senha usuario recebto';
