--------------------------------------------------------
--  DDL for Table CLIENTE_NOTIFICA
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_NOTIFICA" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_NOTIFICA" NUMBER, 
	"DS_TITULO" VARCHAR2(200 BYTE), 
	"DS_NOTIFICACAO" VARCHAR2(2000 BYTE), 
	"LS_USUARIO_DE" VARCHAR2(400 BYTE), 
	"LS_USUARIO_PARA" VARCHAR2(400 BYTE), 
	"DT_ENVIO" DATE, 
	"DT_LEITURA" DATE, 
	"FL_LIDO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;
