--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER, 
	"DS_RAZAO_SOCIAL" VARCHAR2(400 BYTE), 
	"NR_CNPJ" NUMBER(20,0), 
	"DS_NOME_RESP" VARCHAR2(400 BYTE), 
	"NR_RG" NUMBER(20,0), 
	"NR_CPF" NUMBER(20,0), 
	"DS_ENDERECO" VARCHAR2(200 BYTE), 
	"NR_NUMERO" NUMBER(8,0), 
	"DS_COMPLEMENTO" VARCHAR2(400 BYTE), 
	"DS_BAIRRO" VARCHAR2(200 BYTE), 
	"NR_CEP" NUMBER(10,0), 
	"ID_CIDADE" NUMBER, 
	"CD_UF" CHAR(2 BYTE), 
	"DS_TELEFONE1" VARCHAR2(50 BYTE), 
	"DS_EMAIL1" VARCHAR2(200 BYTE), 
	"DS_EMAIL2" VARCHAR2(200 BYTE), 
	"DT_CADASTRO" DATE DEFAULT sysdate, 
	"ST_CLIENTE" CHAR(1 BYTE) DEFAULT 'I', 
	"DS_TITULO" VARCHAR2(200 BYTE), 
	"DS_RODAPE" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE"."DS_EMAIL1" IS 'e-mail principal';
   COMMENT ON COLUMN "WS4TI"."CLIENTE"."DS_EMAIL2" IS 'e-mail alternativo cc';
   COMMENT ON COLUMN "WS4TI"."CLIENTE"."ST_CLIENTE" IS 'Ativo ou Inativo';
   COMMENT ON COLUMN "WS4TI"."CLIENTE"."DS_TITULO" IS 'Titulo padrão do sistema para a empresa';
   COMMENT ON COLUMN "WS4TI"."CLIENTE"."DS_RODAPE" IS 'Rodape padrão do sistema para a empresa';
