--------------------------------------------------------
--  DDL for Table CLIENTE_MAQUINA_CKLIST_ITEM_OS
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS" 
   (	"ID_CLIENTE" NUMBER, 
	"CD_MAQUINA" VARCHAR2(15 BYTE), 
	"SQ_CHECKITEM" NUMBER, 
	"ID_OS" NUMBER, 
	"DT_PROGRAMADA" DATE DEFAULT sysdate, 
	"DS_OBS" VARCHAR2(400 BYTE), 
	"DT_LOG" DATE DEFAULT SYSDATE, 
	"CD_USUARIO_LOG" VARCHAR2(20 BYTE), 
	"QT_TEMPO_PREVISTO" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS"."DT_LOG" IS 'Data da execução da programação';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS"."CD_USUARIO_LOG" IS 'Usuário que executou a programação';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_MAQUINA_CKLIST_ITEM_OS"."QT_TEMPO_PREVISTO" IS 'Quantidade (Minutos) de tempo previsto de execução';
