--------------------------------------------------------
--  DDL for Table CLIENTE_TURNO
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_TURNO" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_TURNO" NUMBER, 
	"NM_TURNO" VARCHAR2(100 BYTE), 
	"DT_INI" DATE, 
	"DT_FIM" DATE, 
	"LS_DSEMANA" CHAR(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_TURNO"."LS_DSEMANA" IS 'Selecionar dia da semana DOM, SEG, TER, QUA, QUI, SEX e SAB';
