--------------------------------------------------------
--  DDL for Table CLIENTE_CONTRATO
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_CONTRATO" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_CONTRATO" NUMBER, 
	"DS_CONTRATO" VARCHAR2(1000 BYTE), 
	"QT_USUARIOS" NUMBER, 
	"DT_CONTRATO" DATE, 
	"DT_VENCIMENTO" DATE, 
	"ST_CONTRATO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."CLIENTE_CONTRATO"."DT_CONTRATO" IS 'Data do cadastro';
   COMMENT ON COLUMN "WS4TI"."CLIENTE_CONTRATO"."ST_CONTRATO" IS 'ATIVO / INATIVO';
