--------------------------------------------------------
--  DDL for Table CLIENTE_MAQUINA_TRO
--------------------------------------------------------

  CREATE TABLE "WS4TI"."CLIENTE_MAQUINA_TRO" 
   (	"ID_CLIENTE" NUMBER, 
	"CD_MAQUINA" VARCHAR2(15 BYTE), 
	"DT_BASE" NUMBER(6,0), 
	"QT_TRO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;
