--------------------------------------------------------
--  DDL for Table MENU_ADM
--------------------------------------------------------

  CREATE TABLE "WS4TI"."MENU_ADM" 
   (	"MNU_ID" NUMBER, 
	"MNU_PAI_ID" NUMBER, 
	"MNU_NOME" VARCHAR2(40 BYTE), 
	"MNU_PAGINA" VARCHAR2(200 BYTE), 
	"MNU_TOOLTIP" VARCHAR2(200 BYTE), 
	"MNU_ORDEM" NUMBER, 
	"MNU_TIPO" VARCHAR2(1 BYTE), 
	"MNU_TECNICO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."MENU_ADM"."MNU_TECNICO" IS 'Mostar na tela dos Técnicos';
