--------------------------------------------------------
--  DDL for Table PARAM_OS_STATUS
--------------------------------------------------------

  CREATE TABLE "WS4TI"."PARAM_OS_STATUS" 
   (	"ST_OS" CHAR(3 BYTE), 
	"DS_STATUS" VARCHAR2(50 BYTE), 
	"FL_ENVIA_EMAIL" CHAR(1 BYTE), 
	"FL_CANCELADO" CHAR(1 BYTE), 
	"NR_NIVEL" NUMBER(2,0), 
	"NR_PRIORIDADE" NUMBER(2,0), 
	"DS_COR_AGENDA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."PARAM_OS_STATUS"."DS_COR_AGENDA" IS 'Cor que o status de OS deve apresentar na agenda';
