--------------------------------------------------------
--  DDL for Table PARAM_OS_EVENTO_TIPO
--------------------------------------------------------

  CREATE TABLE "WS4TI"."PARAM_OS_EVENTO_TIPO" 
   (	"TP_EVENTO" VARCHAR2(3 BYTE), 
	"DS_TIPO" VARCHAR2(50 BYTE), 
	"ST_TIPO" CHAR(1 BYTE) DEFAULT 'A', 
	"ST_OS" CHAR(3 BYTE), 
	"FL_ATENDIMENTO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_273992410125036321" ;

   COMMENT ON COLUMN "WS4TI"."PARAM_OS_EVENTO_TIPO"."TP_EVENTO" IS 'Tipo de evento de OS';
   COMMENT ON COLUMN "WS4TI"."PARAM_OS_EVENTO_TIPO"."ST_TIPO" IS 'Ativo ou Inativo';
   COMMENT ON COLUMN "WS4TI"."PARAM_OS_EVENTO_TIPO"."ST_OS" IS 'Status da OS';
   COMMENT ON COLUMN "WS4TI"."PARAM_OS_EVENTO_TIPO"."FL_ATENDIMENTO" IS 'Sim ou Não - tipo de evento e de atendimento?';
